### ISSUE TITLE
rbenv::build needs environment argument

### ISSUE THREAD

**Issue by hesco** [justindowning/puppet-rbenv#37]
As described here:
https://github.com/sstephenson/ruby-build/issues/526 

This is apparently sufficient to overcome build errors I am encountering in my network, using your module:  

RUBY_CONFIGURE_OPTS=--with-readline-dir="/usr/lib/x86_64-linux-gnu/libreadline.so"

However, the rbenv::build defined type provides no means for passing additional environmental variables across its interface.  

I'm urging an $additional_build_environment => '' parameter permitting one to elegantly use your module to overcome these sort of issues in the upstream ruby build process, as they may crop up from time to time.

**Comment by hesco** [comment]
I was trying to install 2.0.0.-p247 (which had worked for me on Debian last August, when it was the latest version).  My issue was resolved by installing instead 2.2.0, which built on Ubuntu 14.04 tonight without the errors I was trying to resolve half an hour ago when I filed this issue.  

I say that to explain why forking your module to contribute this suggested patch no longer seems to be such a priority for me at the moment.  Although I can still see its utility.  

Thanks for making rbenv available.

**Comment by justindowning** [comment]
You can do this now use the `$env` parameter in `ruby::build` (https://github.com/justindowning/puppet-rbenv/blob/36699a66bc0fe2eee3bda130374516a783b4a0a9/manifests/build.pp#L37-L40). For example:
```
rbenv::build { '2.0.0-p247':
  env => ['RUBY_CONFIGURE_OPTS=--with-readline-dir="/usr/lib/x86_64-linux-gnu/libreadline.so"']
}
```
Another [example](https://github.com/justindowning/puppet-rbenv/blob/36699a66bc0fe2eee3bda130374516a783b4a0a9/tests/vagrant/ubuntu.pp#L11-L18) is in the test directory.

**Comment by hesco** [comment]
You might consider noting this work-around in the README for the benefit of module consumers.  Thanks for the clue.
