### ISSUE TITLE
support for rvm-download plugin?

### ISSUE THREAD

**Issue by jfrost** [justindowning/puppet-rbenv#38]
I found this plugin for downloading precompiled rubies using the rvm repos:

https://github.com/garnieretienne/rvm-download

I see there's already a plugin architecture in the puppet module. I wonder how hard it would be to add the download functionality?

**Comment by justindowning** [comment]
You are correct -- you can already do this via [plugins](https://github.com/justindowning/puppet-rbenv#plugins):
    rbenv::plugin { 'garnieretienne/rvm-download': }

Hope this helps!
