### ISSUE TITLE
Recent release breaks when used with git module

### ISSUE THREAD

**Issue by michaeldfallen** [justindowning/puppet-rbenv#53]
In a the 2.0.0 release the commit https://github.com/justindowning/puppet-rbenv/commit/c01b77007e7cd5924934f43fc8b3afe3fabe81c0 has changed git from an include dependency to a package definition. [Puppetlabs-git](https://github.com/puppetlabs/puppetlabs-git) however doesn't use the safe `ensure_package` declaration but a [direct package declaration](https://github.com/puppetlabs/puppetlabs-git/blob/master/manifests/init.pp#L32).

What this means is anyone using the [Puppetlabs-git](https://github.com/puppetlabs/puppetlabs-git) module now gets the following error message:

```
Error: Duplicate declaration: Package[git] is already declared in file /tmp/vagrant-puppet-4/modules-0/git/manifests/init.pp:34; cannot redeclare at /tmp/vagrant-puppet-4/modules-0/rbenv/manifests/deps/redhat.pp:7 on node dev-vm
```

Unfortunately since you used an `include` before a lot of people will have also used `include` in other modules and not had a problem.

Obviously this can be fixed in [Puppetlabs-git](https://github.com/puppetlabs/puppetlabs-git) but the change will take time to filter down. Is there any way to more safely require the git package?

**Comment by justindowning** [comment]
@michaeldfallen I'm sorry you are having trouble. I believe this has to do with resource ordering. Specifically, the `rbenv` resource is being applied _before_ the `git` resource. Since, as you note, the `git` module assumes it will install the git package exclusively, it is failing since another module installed it beforehand. Can you try re-ordering your modules so that `git` is called before `rbenv`?

**Comment by michaeldfallen** [comment]
@justindowning I'm not sure it is a resource ordering issue. I've used the ordering in `require` and `include` (that require occurs before include) to pull in my git module before pulling in rbenv and the issue still happens. I've switched puppetlabs-git to do an `ensure_packages` and that's fixed it https://github.com/puppetlabs/puppetlabs-git/compare/master...michaeldfallen:safe-ensure.

I think the main problem here is that the change you've made, from `include ::git` to `ensure_packages` changes the `ensure` directive being applied to `git`. In `include ::git` it's `ensure => installed` in your `ensure_packages` it's `ensure => present`. I think puppet is taking this to be two different declarations and then complaining that you can't declare it twice.

**Comment by justindowning** [comment]
@michaeldfallen Can you test if the recently merged #57 fixes this for you?

**Comment by walkamongus** [comment]
Just an FYI -- I just ran into this issue using v2.1.0.

**Comment by justindowning** [comment]
@walkamongus You should be able to disable dependency managment with v2.1.0:
```
class { 'rbenv':
  manage_deps => false
}
```
