### ISSUE TITLE
issues installing rubies

### ISSUE THREAD

**Issue by chewmanfoo** [justindowning/puppet-rbenv#55]
I'm using puppet 3.7.5  deploying to CentOS 6.6.

I use the following in my manifest:

     class { 'rbenv':
         install_dir => '/opt/rbenv'
     }

     rbenv::plugin { 'sstephenson/ruby-build': }
     rbenv::build { '2.2.3': global => true }

rbenv loads properly, and ruby 2.2.3 loads properly in that a working ruby is placed inn /opt/rbenv/versions/2.2.3.

However, when you try to use the ruby that's loaded, it doesn't work properly.

     root@mgmtlin.i-a1830774:~/test# ruby --version
     ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
     root@mgmtlin.i-a1830774:~/test# /opt/rbenv/versions/2.2.3/bin/ruby --version
     ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

     root@mgmtlin.i-a1830774:~/test# cd ruby
     root@mgmtlin.i-a1830774:~/test/ruby# cat .ruby-version
     2.2.3
     root@mgmtlin.i-a1830774:~/test/ruby# ruby --version
     ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
     root@mgmtlin.i-a1830774:~/test/ruby# rbenv versions
     rbenv: version `2.2.3' is not installed (set by /root/test/ruby/.ruby-version)
      system
     root@mgmtlin.i-a1830774:~/test/ruby# rbenv local
     2.2.3

It appears that a symlink in ~/.rbenv/ called 'versions' which points to /opt/rbenv/versions fixes the issue.  Is this something expected, or a defect?

**Comment by justindowning** [comment]
I appears your profile is not sourced. First, make sure `/etc/profile.d/rbenv.sh` exists and sets `RBENV_ROOT=/opt/rbenv`. Then ensure your `/etc/profile` is sourced in your shell (see #55).
