### ISSUE TITLE
$manage_deps issue for RHEL & CentOS Users

### ISSUE THREAD

**Issue by itsnotify** [justindowning/puppet-rbenv#60]
Hi,

We've recently started using this module and are generally pleased with how effective it is. Unfortunately we've discovered an issue when deploying to our CentOS 7 servers via Puppet Code Manager:

The problems are around the "$manage_deps" option. We have to set "$manage_deps = false," as we already install git elsewhere.

The problem is that you still have the following set in init.pp:
`exec { 'git-clone-rbenv':
    command     => "/usr/bin/git clone ${rbenv::repo_path} ${install_dir}",
    creates     => $install_dir,
    cwd         => '/',
    user        => $owner,
    environment => $env,
    require     => Package['git'],
  }`

If you look at https://git-scm.com/download/linux you'll note that Red Hat & CentOS users are advised to obtain packages from the IUS repo in order to get newer versions of Git. As such, many of our servers are using their git2u packages to get Git 2.9.1.

Unfortunately using the git2u packages mean we can't also have a package called "git" installed! It's an immediate conflict: "Error: git2u conflicts with git-1.8.3.1-6.el7_2.1.x86_64"

Please can you update your manifest so that if "$manage_deps" is false you don't have this "require"? Obviously it's fine to have it for users with "manage_deps" set to true.

Thanks

**Comment by itsnotify** [comment]
Hi,

As I've not had any response I've elected to fork your code and fix the issue locally myself. When looking more closely at the module I noticed it's using a lot of git pulls.

I've reworked parts of the module to use Puppetlabs vcsrepo module for all the git checkouts. This makes the rbenv module much smaller and easier to understand.

The current code is available here: https://github.com/JadesFire/puppet-rbenv/ (it's a work in progress and still needs metadata updates, tags etc).

I'd be happy to do some more tweaking and then create a merge request, otherwise I can continue on my own. 

Either way thanks to you and your co-devs for creating a great module.

**Comment by justindowning** [comment]
Thanks for this issue here. I removed the git package requirement as you suggested. As for using `vcsrepo`, that looks like an interesting approach. If you want to PR for inclusion here I'd be happy to take a look. Don't forget to update [dependencies](https://github.com/justindowning/puppet-rbenv/blob/f1fd8bba4691b822a033643ee7ec3b546ffdb43d/metadata.json#L13) too. 💚
