### ISSUE TITLE
New release on the Forge

### ISSUE THREAD

**Issue by madAndroid** [justindowning/puppet-rbenv#64]
Hi,

Would it be possible to get a new release published to the Forge? Although we can install from Git in Librarian-Puppet, it's preferable to pin to a version range in the Forge, as this gives us more flexibility.

Thanks!
Andrew

**Comment by justindowning** [comment]
Hot of the presses! I just released `2.2.0` to the [Forge](https://forge.puppet.com/jdowning/rbenv/readme). 🎉

**Comment by madAndroid** [comment]
Awesome, thanks!
