### ISSUE TITLE
Timing of next release

### ISSUE THREAD

**Issue by olorin** [justindowning/puppet-rbenv#74]
Hi, just wondering if you're planning on cutting a release any time soon? I need support for configurable sources, which you have [in master](https://github.com/justindowning/puppet-rbenv/pull/68) but not yet on puppetforge.

Thanks!

**Comment by justindowning** [comment]
No problem! I just released 2.3.0 to [puppetforge](https://forge.puppet.com/jdowning/rbenv). 🎉

**Comment by olorin** [comment]
Awesome, thanks. 👍
